const mongoose = require("mongoose");

// One entry in the audit trail — every status change gets logged here so the
// owner dashboard can show a full history per ticket.
const auditEntrySchema = new mongoose.Schema(
  {
    action: {
      type: String,
      required: true, // e.g. "CREATED", "PAYMENT_UPDATED", "CLOSED", "REOPENED"
    },
    agentId: { type: String }, // loginId of the agent who performed it
    agentName: { type: String },
    note: { type: String },
    at: { type: Date, default: Date.now },
  },
  { _id: false }
);

const ticketSchema = new mongoose.Schema(
  {
    // Generated ON THE DEVICE at creation time (UUID v4) — NOT the Mongo _id.
    // This is what makes offline-first, conflict-free sync possible: every
    // agent's phone can create tickets independently with no collision risk,
    // and syncing is a simple upsert keyed on this field.
    ticketId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // ---- Vehicle / OCR data ----
    plateNumber: {
      type: String,
      required: true,
      uppercase: true,
      trim: true,
    },
    ocrRawText: { type: String }, // whatever ML Kit originally read, pre-correction
    ocrConfidence: { type: Number }, // optional 0-1 score from ML Kit if available

    // Photo stored as base64 (offline-created, synced as-is). Swap for an
    // object-storage URL later if payload size becomes a problem.
    photoBase64: { type: String, required: true },

    // ---- QR / security ----
    // HMAC-SHA256 signature of ticketId, generated by the backend when the
    // ticket is first synced (source of truth) so it can't be forged client-side
    // even though the QR is displayed offline immediately after creation using
    // a device-local signature — see qrSignedOffline flag.
    qrSignature: { type: String, required: true },
    qrSignedOffline: { type: Boolean, default: false }, // true until backend re-verifies on first sync

    // ---- Status / lifecycle ----
    status: {
      type: String,
      enum: ["OPEN", "CLOSED"],
      default: "OPEN",
      index: true,
    },

    // ---- Payment ----
    paymentStatus: {
      type: String,
      enum: ["PAID", "PENDING", "UNPAID"], // UNPAID = customer refused at exit
      default: "PENDING",
    },
    paymentMethod: {
      type: String,
      enum: ["CASH", "UPI", "NONE"],
      default: "NONE",
    },
    feeAmount: { type: Number, default: 0 }, // auto-calculated at exit, 0 until then

    // ---- Razorpay real-time UPI payment (optional — cash/manual still works) ----
    upi: {
      qrId: { type: String }, // Razorpay QR Code entity id
      qrImageUrl: { type: String },
      status: {
        type: String,
        enum: ["NONE", "CREATED", "PAID", "EXPIRED", "CANCELLED"],
        default: "NONE",
      },
      paymentId: { type: String }, // Razorpay payment entity id, set once credited
      amount: { type: Number }, // paise, what the QR was generated for
      createdAt: { type: Date },
    },

        // ---- Fallback: Razorpay Payment Links (upi_link), used if the QR Code
    // API isn't API-enabled on this account. Same idea, different product. ----
    paymentLink: {
      linkId: { type: String },
      shortUrl: { type: String },
      status: {
        type: String,
        enum: ["NONE", "CREATED", "PAID", "EXPIRED", "CANCELLED"],
        default: "NONE",
      },
      paymentId: { type: String },
      amount: { type: Number }, // paise
      createdAt: { type: Date },
    },

    // ---- Entry ----
    entryAgentId: { type: String, required: true }, // loginId
    entryAgentName: { type: String, required: true },
    entryTime: { type: Date, required: true },

    // ---- Exit ----
    exitAgentId: { type: String },
    exitAgentName: { type: String },
    exitTime: { type: Date },

    // ---- Sync bookkeeping (for offline-first conflict handling) ----
    createdOffline: { type: Boolean, default: false },
    lastSyncedAt: { type: Date, default: Date.now },
    deviceId: { type: String }, // which agent phone originated this record

    // ---- Audit trail ----
    audit: [auditEntrySchema],

    // ---- Auto-purge ----
    // Set only once the ticket is CLOSED. MongoDB TTL index below deletes the
    // document automatically once this timestamp passes — no cron job needed.
    deleteAfter: { type: Date, default: null },
  },
  { timestamps: true }
);

// TTL index — MongoDB's background task sweeps documents once deleteAfter is
// in the past. expireAfterSeconds: 0 means "delete exactly at the stored date".
ticketSchema.index({ deleteAfter: 1 }, { expireAfterSeconds: 0 });

// Helpful compound index for dashboard queries (status + time range)
ticketSchema.index({ status: 1, entryTime: -1 });

module.exports = mongoose.model("Ticket", ticketSchema);
